package it.reef.ark.rmi.scoreservice;

// Generated 18-feb-2011 14.27.11 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Punteggio generated by hbm2java
 */
public class Punteggio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nome;
	private Date dataInserimento;
	private long punteggio;

	public Punteggio() {
	}

	public Punteggio(String nome, Date dataInserimento, long punteggio) {
		this.nome = nome;
		this.dataInserimento = dataInserimento;
		this.punteggio = punteggio;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Date getDataInserimento() {
		return this.dataInserimento;
	}

	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	public long getPunteggio() {
		return this.punteggio;
	}

	public void setPunteggio(long punteggio) {
		this.punteggio = punteggio;
	}

}
